name: OpenNetMeter → Update Single Draft Release

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore .\OpenNetMeter.sln

      - name: Build solution (Release)
        run: dotnet build .\OpenNetMeter.sln --configuration Release --no-restore

      # ─── Create (or update) a single Draft Release ─────────────────────────
      - name: Create or update draft release
        id: draft_release
        uses: actions/create-release@v1
        with:
          tag_name: opennetmeter-draft
          release_name: "OpenNetMeter (Draft Release)"
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ─── Upload the .msi into that Draft Release (overwrite each run) ──────
      - name: Upload MSI to draft release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          # Use a glob (**) to find the .msi regardless of exact subfolder depth
          path: |
            **/Installer/bin/x64/Release/en-us/OpenNetMeter-*.msi
          asset_name: OpenNetMeter-latest.msi
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
