# This workflow will build a .NET project
# For more information see httpsdocs.github.comenactionsautomating-builds-and-testsbuilding-and-testing-net

name .NET

on
  push
    branches [ main ]
  pull_request
    branches [ main ]

jobs
  build

    runs-on ubuntu-latest

    steps
    - uses actionscheckout@v4
    - name Setup .NET
      uses actionssetup-dotnet@v4
      with
        dotnet-version 8.0.x
    - name Restore dependencies
      run dotnet restore
    - name Build
      run dotnet build --no-restore
    - name Test
      run dotnet test --no-build --verbosity normal
