name: OpenNetMeter → Update Single Draft Release

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore .\OpenNetMeter.sln

      - name: Build solution (Release)
        run: dotnet build .\OpenNetMeter.sln --configuration Release --no-restore

      # ─── Find the exact MSI path ────────────────────────────────────
      - name: Find built MSI
        id: find_msi
        shell: pwsh
        run: |
          $installer = Join-Path $Env:GITHUB_WORKSPACE 'Installer\bin\x64\Release\en-us'
          $msi = Get-ChildItem -Path $installer -Filter 'OpenNetMeter-*.msi' | Select-Object -First 1
          if (-not $msi) { throw '❌ No MSI found in Installer/bin/x64/Release/en-us' }

          # Emit a relative path (forward‐slashes) so the release-action can pick it up
          $rel = "Installer/bin/x64/Release/en-us/$($msi.Name)"
          Write-Host "msi_path=$rel" >> $Env:GITHUB_OUTPUT

      # ─── Create or update the one Draft Release & upload the MSI ────
      - name: Publish draft release (create or update)
        uses: ncipollo/release-action@v1
        with:
          token:       ${{ secrets.GITHUB_TOKEN }}
          tag:         opennetmeter-draft
          name:        "OpenNetMeter (Draft Release)"
          draft:       true
          allowUpdates: true
          artifacts:   ${{ steps.find_msi.outputs.msi_path }}
