name: Build OpenNetMeter MSI and Push to Single Draft Release

on:
  workflow_dispatch:
 
# Give the release-action permission to create/update releases & assets
permissions:
  contents: write

jobs:
  draft-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build Release
        run: |
          dotnet restore .\OpenNetMeter.sln
          dotnet build   .\OpenNetMeter.sln --configuration Release --no-restore

      - name: Find built MSI
        id: find_msi
        shell: pwsh
        run: |
          $msi = Get-ChildItem `
            "$Env:GITHUB_WORKSPACE\Installer\bin\x64\Release\en-us" `
            -Filter 'OpenNetMeter-*.msi' `
            | Select-Object -First 1
          if (-not $msi) { throw '❌ No MSI found!' }
          # Emit the *absolute* path:
          Write-Host "msi_path=$($msi.FullName)" >> $Env:GITHUB_OUTPUT

      - name: Create or Update Draft Release & Upload MSI
        uses: ncipollo/release-action@v1
        with:
          token:        ${{ secrets.GITHUB_TOKEN }}
          tag:          opennetmeter-draft
          name:         OpenNetMeter (Draft Release)
          draft:        true
          allowUpdates: true
          artifacts:    C:\a\OpenNetMeter\OpenNetMeter\Installer\bin\x64\Release\en-us\OpenNetMeter-0.13.0.msi
