name: Build OpenNetMeter MSI and Push to Single Draft Release

on:
  workflow_dispatch:

jobs:
  draft-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build Release
        run: |
          dotnet restore .\OpenNetMeter.sln
          dotnet build   .\OpenNetMeter.sln --configuration Release --no-restore

      - name: Find built MSI
        id: find_msi
        shell: pwsh
        run: |
          $folder = Join-Path $Env:GITHUB_WORKSPACE 'Installer\bin\x64\Release\en-us'
          $msi = Get-ChildItem $folder -Filter 'OpenNetMeter-*.msi' | Select-Object -First 1
          if (-not $msi) { throw '❌ No MSI found!' }
          # emit a forward-slash relative path and the filename
          $rel = $msi.FullName.Substring($Env:GITHUB_WORKSPACE.Length+1).Replace('\','/')
          Write-Host "msi_path=$rel" >> $Env:GITHUB_OUTPUT
          Write-Host "msi_name=$($msi.Name)" >> $Env:GITHUB_OUTPUT

      - name: Create or Update Draft Release & Upload MSI
        uses: ncipollo/release-action@v1
        with:
          token:        ${{ secrets.GITHUB_TOKEN }}
          tag:          opennetmeter-draft
          name:         OpenNetMeter (Draft Release)
          draft:        true
          allowUpdates: true
          artifacts:    ${{ steps.find_msi.outputs.msi_path }}
