name: Build OpenNetMeter msi and push to Single Draft Release

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore .\OpenNetMeter.sln

      - name: Build solution (Release)
        run: dotnet build .\OpenNetMeter.sln --configuration Release --no-restore

      - name: Create or update draft release
        id: draft_release
        uses: actions/create-release@v1
        with:
          tag_name: opennetmeter-draft
          release_name: "OpenNetMeter (Draft Release)"
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find built MSI
        id: find_msi
        shell: pwsh
        run: |
          # Look for the MSI in the installer output folder
          $msi = Get-ChildItem -Path "$PWD\Installer\bin\x64\Release\en-us" -Filter "OpenNetMeter-*.msi" | Select-Object -First 1
          if (-not $msi) { throw "❌ No MSI found in Installer/bin/x64/Release/en-us" }
          # Emit the path *relative* to the repo root (remove the working-dir prefix)
          $rel = $msi.FullName.Substring($PWD.Length + 1) 
          Write-Host "msi_path=$rel" >> $Env:GITHUB_OUTPUT

      - name: Upload MSI to draft release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: ${{ steps.find_msi.outputs.msi_path }}
          asset_name: OpenNetMeter-latest.msi
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
