name: OpenNetMeter → Update Single Draft Release

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore .\OpenNetMeter.sln

      - name: Build solution (Release)
        run: dotnet build .\OpenNetMeter.sln --configuration Release --no-restore

      - name: Find built MSI
        id: find_msi
        shell: pwsh
        run: |
          # Where the MSI lands
          $installerFolder = Join-Path $Env:GITHUB_WORKSPACE 'Installer\bin\x64\Release\en-us'
          $msi = Get-ChildItem $installerFolder -Filter 'OpenNetMeter-*.msi' | Select-Object -First 1
          if (-not $msi) { throw '❌ No MSI found!' }

          # Strip off the workspace prefix and normalize to forward-slashes
          $rel = $msi.FullName
            .Substring($Env:GITHUB_WORKSPACE.Length + 1)
            .Replace('\','/')
          Write-Host "msi_path=$rel" >> $Env:GITHUB_OUTPUT

      - name: Create or update draft release & upload MSI
        uses: ncipollo/release-action@v1
        with:
          token:        ${{ secrets.GITHUB_TOKEN }}
          tag:          opennetmeter-draft
          name:         "OpenNetMeter (Draft Release)"
          draft:        true
          allowUpdates: true
          files:        ${{ steps.find_msi.outputs.msi_path }}
