# This workflow will build a .NET project
# For more information see httpsdocs.github.comenactionsautomating-builds-and-testsbuilding-and-testing-net

name: Build the agent

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type: Release (default) or debug"
        required: true
        default: "release"
        type: choice
        options:
          - release
          - debug

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actionscheckout@v4
    - name: Setup .NET
      uses: actionssetup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
