# This workflow will build a .NET project
# For more information see httpsdocs.github.comenactionsautomating-builds-and-testsbuilding-and-testing-net

name: Build the agent

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type: Release (default) or debug"
        required: true
        default: "release"
        type: choice
        options:
          - release
          - debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Restore dependencies
      run: dotnet restore
